baseurl = "https://burhan-techblogs.netlify.app/"
languageCode = "en-us"
theme = "terminal"
paginate = 8

[params]
  contentTypeName = "posts"
  themeColor = "blue"
  showLanguageSelector = false
  fullWidthTheme = false
  centerTheme = true
  autoCover = false
  showLastUpdated = false
  readingTime = true 
  Toc = true
  TocTitle = "Table of Contents"


[params.twitter]
  creator = "Burhan Raja"
  site = ""

[languages]
  [languages.en]
    languageName = "English"
    title = "Tech and Development"
    subtitle = "Programming, Computer Science, tech stacks and many more"
    owner = "Burhanuddin Raja"
    keywords = ""
    copyright = "Burhanuddin Raja"
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    newerPosts = "Newer posts"
    olderPosts = "Older posts"
    missingContentMessage = "Page not found..."
    missingBackButtonLabel = "Back to home page"

    [languages.en.params.logo]
      logoText = "Terminal"
      logoHomeLink = "/"