# baseURL = "https://burhan-codingblogs.netlify.app/"
baseURL = "http://localhost:1313/"
languageCode = "en-us"
theme = "hugo-theme-terminal"
paginate = 8

[params]
  contentTypeName = "posts"
  themeColor = "blue"
  fullWidthTheme = true
  centerTheme = true

[params.twitter]
  creator = "Burhan Raja"
  site = "https://twitter.com/Burhan_Raja52"

[languages]
  [languages.en]
    title = "Programming Blogs"
    subtitle = "A simple, retro theme for Hugo"
    keywords = "Software Engineer Technology Blogs"
    copyright = "Burhanuddin Raja"
    readMore = "Read more"
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "Terminal"
      logoHomeLink = "/"


